# unity
unityStreamingAssets=
unityTemplateVersion=7

# jvm tuning
org.gradle.jvmargs=-Xmx8192M -XX:+UseG1GC -XX:MaxMetaspaceSize=1024m

# gradle performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.welcome=never
org.gradle.tooling.parallel=true

# AGP settings
android.useAndroidX=true
android.nonTransitiveRClass=true
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=true
