name: Android CI

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        if: github.ref_type != 'tag'
        run: ./gradlew assembleDebug

      - name: Decode keystore
        if: github.ref_type == 'tag'
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ${{ runner.temp }}/keystore.jks

      - name: Build Release APK
        if: github.ref_type == 'tag'
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PATH: ${{ runner.temp }}/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Debug APK
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v6
        with:
          name: fusionApp-debug
          path: fusionApp/build/outputs/apk/debug/*.apk

      - name: Upload Release APK
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v6
        with:
          name: fusionApp-release-${{ github.ref_name }}
          path: fusionApp/build/outputs/apk/release/*.apk

      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: fusionApp/build/outputs/apk/release/*.apk